import json
import uuid
from collections import defaultdict, deque
from datetime import datetime
from pathlib import Path
from typing import Any, Literal

from openai import pydantic_function_tool
from pydantic import BaseModel, Field

from init import WORKDIR

TASKS_DIR = WORKDIR / ".tasks"

VALID_STATUS = {
    "pending",
    "in_progress",
    "completed",
}


class CreateTask(BaseModel):
    """
    Create one new task.
    Use this when you want to append a single executable unit to the topology plan.
    `task_id` is auto-generated by TaskManager; do not provide `task_id` in input.
    Constraints:
    - `subject` is required and cannot be empty.
    - `depend_on` can only contain existing task IDs.
    - Task will be topology-validated after insertion.
    """
    subject: str = Field(..., min_length=1, description="Task title, concise and action-oriented.")
    description: str = Field(default="", description="Optional detailed description for the task.")
    depend_on: list[str] = Field(default_factory=list, description="IDs of tasks this task depends on.")
    status: Literal["pending", "in_progress", "completed"] = Field(
        default="pending",
        description="Initial task status."
    )


class UpdateTaskStatus(BaseModel):
    """
    Update one task's status.
    Constraints:
    - task must exist
    - status must be one of pending/in_progress/completed
    """
    task_id: str = Field(..., min_length=1, description="Target task ID.")
    status: Literal["pending", "in_progress", "completed"] = Field(
        ...,
        description="New status for the task."
    )


class UpdateTaskDependencies(BaseModel):
    """
    Rewrite one task's dependency list.
    Use this to correct or adjust execution ordering.
    Constraints:
    - all dependencies must exist
    - task cannot depend on itself
    - dependency update must pass topology validation
    """
    task_id: str = Field(..., min_length=1, description="Target task ID.")
    depend_on: list[str] = Field(default_factory=list, description="New full dependency list.")


class GetTask(BaseModel):
    """Get one task's full detail by ID."""
    task_id: str = Field(..., min_length=1, description="Target task ID.")


class GetRunnableTasks(BaseModel):
    """
    Get current runnable frontier tasks.
    Runnable means:
    - status is `pending`
    - all dependencies are `completed`
    - completed tasks are excluded from topology consideration
    Usage rule:
    - Call this immediately before DelegateTasks and only delegate tasks returned here.
    """


class GetTaskTable(BaseModel):
    """
    Get LLM-friendly detailed task table.
    Returns a compact structured payload with summary + rows,
    designed for direct model context consumption.
    """


def _now_iso() -> str:
    return datetime.now().isoformat()


class TaskManager:
    """
    Agent-facing topology task manager.
    Per-task APIs:
      1) create_task
      2) update_task_status
      3) update_task_dependencies
      4) get_task
    Manager APIs:
      5) get_runnable_tasks
      6) get_task_table
    """

    def __init__(self, workspace: Path = TASKS_DIR):
        self.workspace = workspace
        self.workspace.mkdir(parents=True, exist_ok=True)
        epic_id = uuid.uuid4().hex[:8]
        self.path = self.workspace / f"task_plan_{epic_id}.json"
        now = _now_iso()
        self._data: dict[str, Any] = {
            "epic_id": epic_id,
            "epic_subject": "Main Project Task",
            "next_id": 1,
            "created_at": now,
            "updated_at": now,
            "tasks": {},
        }

    def _save(self) -> None:
        self._data["updated_at"] = _now_iso()
        self.path.write_text(json.dumps(self._data, indent=2, ensure_ascii=False), encoding="utf-8")

    @staticmethod
    def _id_str(task_id: str | int) -> str:
        return str(task_id)

    @staticmethod
    def _id_sort_key(task_id: str) -> tuple[int, str]:
        return (0, f"{int(task_id):020d}") if task_id.isdigit() else (1, task_id)

    def _ensure_task_exists(self, task_id: str | int) -> str:
        tid = self._id_str(task_id)
        if tid not in self._data["tasks"]:
            raise ValueError(f"Task {task_id} not found")
        return tid

    def _ensure_tasks_exist(self, task_ids: list[str | int]) -> list[str]:
        ids = [self._id_str(x) for x in task_ids]
        missing = [x for x in ids if x not in self._data["tasks"]]
        if missing:
            raise ValueError(f"Tasks not found: {missing}")
        return ids

    def _task(self, task_id: str | int) -> dict[str, Any]:
        return self._data["tasks"][self._ensure_task_exists(task_id)]

    def _validate_status(self, status: str) -> None:
        if status not in VALID_STATUS:
            raise ValueError(f"Invalid status '{status}', must be one of {sorted(VALID_STATUS)}")

    def _touch_task(self, task: dict[str, Any]) -> None:
        task["updated_at"] = _now_iso()

    def _active_task_ids(self) -> set[str]:
        return {tid for tid, task in self._data["tasks"].items() if task["status"] != "completed"}

    def _validate_topology(self) -> None:
        """
        Validate DAG among active tasks.
        Completed tasks are excluded from topology calculation.
        """
        tasks = self._data["tasks"]
        active = self._active_task_ids()

        indegree = {tid: 0 for tid in active}
        graph: dict[str, list[str]] = defaultdict(list)
        for tid in active:
            for dep in tasks[tid].get("depend_on", []):
                if dep in active:
                    graph[dep].append(tid)
                    indegree[tid] += 1

        q = deque(sorted([tid for tid, deg in indegree.items() if deg == 0], key=self._id_sort_key))
        visited = 0
        while q:
            cur = q.popleft()
            visited += 1
            for nxt in graph.get(cur, []):
                indegree[nxt] -= 1
                if indegree[nxt] == 0:
                    q.append(nxt)

        if visited != len(active):
            cycle_nodes = sorted([tid for tid, deg in indegree.items() if deg > 0], key=self._id_sort_key)
            raise ValueError(f"Cycle detected among active tasks: {cycle_nodes}")

    # -------- Per-task APIs --------
    def create_task(
            self,
            subject: str,
            description: str = "",
            depend_on: list[str | int] | None = None,
            status: str = "pending",
            **kwargs
    ) -> dict[str, Any]:
        subject = (subject or "").strip()
        if not subject:
            raise ValueError("subject is required")
        self._validate_status(status)

        dep_ids = [self._id_str(x) for x in (depend_on or [])]
        self._ensure_tasks_exist(dep_ids)

        task_id = str(self._data["next_id"])
        if task_id in dep_ids:
            raise ValueError("Task cannot depend on itself")

        now = _now_iso()
        task = {
            "id": task_id,
            "subject": subject,
            "description": description,
            "status": status,
            "depend_on": sorted(set(dep_ids), key=self._id_sort_key),
            "created_at": now,
            "updated_at": now,
        }
        self._data["tasks"][task_id] = task
        self._data["next_id"] += 1

        # Task count changed -> must validate topology.
        self._validate_topology()
        self._save()
        return task

    def update_task_status(self, task_id: str | int, status: str, **kwargs) -> dict[str, Any]:
        self._validate_status(status)
        task = self._task(task_id)
        task["status"] = status
        self._touch_task(task)
        self._save()
        return task

    def update_task_dependencies(self, task_id: str | int, depend_on: list[str | int], **kwargs) -> dict[str, Any]:
        tid = self._ensure_task_exists(task_id)
        dep_ids = [self._id_str(x) for x in depend_on]
        self._ensure_tasks_exist(dep_ids)
        if tid in dep_ids:
            raise ValueError("Task cannot depend on itself")
        task = self._data["tasks"][tid]
        task["depend_on"] = sorted(set(dep_ids), key=self._id_sort_key)
        self._touch_task(task)
        self._validate_topology()
        self._save()
        return task

    def get_task(self, task_id: str | int, **kwargs) -> dict[str, Any]:
        return self._task(task_id)

    # -------- Manager APIs --------
    def get_runnable_tasks(self, **kwargs) -> list[dict[str, Any]]:
        tasks = self._data["tasks"]
        runnable = []
        for _, task in tasks.items():
            if task["status"] != "pending":
                continue
            if all(
                    dep in tasks and tasks[dep]["status"] == "completed"
                    for dep in task.get("depend_on", [])
            ):
                runnable.append(task)
        return sorted(runnable, key=lambda t: self._id_sort_key(t["id"]))

    def get_task_table(self, **kwargs) -> dict[str, Any]:
        tasks = sorted(self._data["tasks"].values(), key=lambda t: self._id_sort_key(t["id"]))
        runnable_ids = {t["id"] for t in self.get_runnable_tasks()}
        status_count = {"pending": 0, "in_progress": 0, "completed": 0}
        rows = []
        for t in tasks:
            status = t["status"]
            if status in status_count:
                status_count[status] += 1
            rows.append(
                {
                    "id": t["id"],
                    "subject": t["subject"],
                    "status": status,
                    "depend_on": t.get("depend_on", []),
                    "is_runnable": t["id"] in runnable_ids,
                    "description": t.get("description", ""),
                    "updated_at": t.get("updated_at"),
                }
            )

        return {
            "summary": {
                "epic_id": self._data["epic_id"],
                "epic_subject": self._data["epic_subject"],
                "total": len(tasks),
                "pending": status_count["pending"],
                "in_progress": status_count["in_progress"],
                "completed": status_count["completed"],
                "runnable_count": len(runnable_ids),
            },
            "columns": [
                "id",
                "subject",
                "status",
                "depend_on",
                "is_runnable",
                "description",
                "updated_at",
            ],
            "rows": rows,
        }


TASK_MANAGER = TaskManager()

TOOLS = [
    pydantic_function_tool(CreateTask),
    pydantic_function_tool(UpdateTaskStatus),
    pydantic_function_tool(UpdateTaskDependencies),
    pydantic_function_tool(GetTask),
    pydantic_function_tool(GetRunnableTasks),
    pydantic_function_tool(GetTaskTable),
]

TASK_MANAGER_NAMESPACE = {
    "type": "namespace",
    "name": "TaskManager",
    "description": (
        "Task topology planning and execution state tools. "
        "Recommended flow: CreateTask -> UpdateTaskDependencies -> GetRunnableTasks -> DelegateTasks "
        "(DelegateTasks lives in Team tools and should only receive runnable task IDs)."
    ),
    "tools": TOOLS,
}

TASK_MANAGER_TOOLS = [
    TASK_MANAGER_NAMESPACE,
]

TASK_MANAGER_TOOLS_HANDLERS = {
    "CreateTask": TASK_MANAGER.create_task,
    "UpdateTaskStatus": TASK_MANAGER.update_task_status,
    "UpdateTaskDependencies": TASK_MANAGER.update_task_dependencies,
    "GetTask": TASK_MANAGER.get_task,
    "GetRunnableTasks": TASK_MANAGER.get_runnable_tasks,
    "GetTaskTable": TASK_MANAGER.get_task_table,
}
